import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Confetti from "react-confetti";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [width, setWhidt] = useState(700);
  const [numberOfPieces, setNumberOfPieces] = useState(50);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="inputWhidt">
          <label for="input_width">Larghezza</label>
          <input
            onChange={(e) => setWhidt(e.target.value * 15)}
            type="range"
            name="input_width"
            id="input_width"
          />
          <p>Larghezza:{width}</p>
        </div>

        <div className="numberOfPieces">
          <label for="numberOfPieces">Numero di coriandoli</label>
          <input
            onChange={(e) => setNumberOfPieces(e.target.value * 2)}
            type="range"
            name="input_numberOfPieces"
            id="input_numberOfPieces"
          />
          <p>pezzi:{numberOfPieces}</p>
        </div>
      </main>
      <div className={styles.confetti}>
        <Confetti width={width} numberOfPieces={numberOfPieces} />
      </div>
    </>
  );
}
