import Head from "next/head";
import globalReducer from "@/store/reducers";
import { useReducer } from "react";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import AddNote from "@/components/addNote";
import { initialState, listContext } from "@/store";
import ItemList from "@/components/itemList";
import Searchbar from "@/components/searchbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [state, dispatch] = useReducer(globalReducer, initialState);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <listContext.Provider value={{ state, dispatch }}>
        <div className={styles}>
          <AddNote />
          <Searchbar />
          <ItemList />
        </div>
      </listContext.Provider>
    </>
  );
}
